package lt.vu.usecases.mybatis.model;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ADDRESS
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.PASSWORDDIGEST
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private String passworddigest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.USERNAME
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @return the value of PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @param id the value for PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ADDRESS
     *
     * @return the value of PUBLIC.CUSTOMER.ADDRESS
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ADDRESS
     *
     * @param address the value for PUBLIC.CUSTOMER.ADDRESS
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @return the value of PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @param firstname the value for PUBLIC.CUSTOMER.FIRSTNAME
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @return the value of PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @param lastname the value for PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.PASSWORDDIGEST
     *
     * @return the value of PUBLIC.CUSTOMER.PASSWORDDIGEST
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public String getPassworddigest() {
        return passworddigest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.PASSWORDDIGEST
     *
     * @param passworddigest the value for PUBLIC.CUSTOMER.PASSWORDDIGEST
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setPassworddigest(String passworddigest) {
        this.passworddigest = passworddigest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.USERNAME
     *
     * @return the value of PUBLIC.CUSTOMER.USERNAME
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.USERNAME
     *
     * @param username the value for PUBLIC.CUSTOMER.USERNAME
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }
}