package lt.vu.usecases.mybatis.model;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDERS.ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDERS.COMMENT
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDERS.DATE
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDERS.CUSTOMER_ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private Integer customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDERS.ID
     *
     * @return the value of PUBLIC.ORDERS.ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDERS.ID
     *
     * @param id the value for PUBLIC.ORDERS.ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDERS.COMMENT
     *
     * @return the value of PUBLIC.ORDERS.COMMENT
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDERS.COMMENT
     *
     * @param comment the value for PUBLIC.ORDERS.COMMENT
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDERS.DATE
     *
     * @return the value of PUBLIC.ORDERS.DATE
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDERS.DATE
     *
     * @param date the value for PUBLIC.ORDERS.DATE
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDERS.CUSTOMER_ID
     *
     * @return the value of PUBLIC.ORDERS.CUSTOMER_ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDERS.CUSTOMER_ID
     *
     * @param customerId the value for PUBLIC.ORDERS.CUSTOMER_ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
}