package lt.vu.usecases.mybatis.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.PRODUCT_CATEGORY_ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    private Integer productCategoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.ID
     *
     * @return the value of PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.ID
     *
     * @param id the value for PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.NAME
     *
     * @return the value of PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.NAME
     *
     * @param name the value for PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.PRODUCT_CATEGORY_ID
     *
     * @return the value of PUBLIC.PRODUCT.PRODUCT_CATEGORY_ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public Integer getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.PRODUCT_CATEGORY_ID
     *
     * @param productCategoryId the value for PUBLIC.PRODUCT.PRODUCT_CATEGORY_ID
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    public void setProductCategoryId(Integer productCategoryId) {
        this.productCategoryId = productCategoryId;
    }
}