package lt.vu.usecases.mybatis.dao;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORDERS
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORDERS
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORDERS
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORDERS
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORDERS
     *
     * @mbg.generated Wed May 08 08:44:06 EEST 2019
     */
    int updateByPrimaryKey(Order record);
}